// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg0AwcQ11I_7Mg-SEm9Aa1QbaV2yRJjUQ',
    appId: '1:781616472859:web:cd36a2a98d00f5233de9be',
    messagingSenderId: '781616472859',
    projectId: 'tourmatelk-a98cb',
    authDomain: 'tourmatelk-a98cb.firebaseapp.com',
    storageBucket: 'tourmatelk-a98cb.firebasestorage.app',
    measurementId: 'G-CMJC52MM5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeY84xYHoRqLGAQzaRE2k9MkTtjuAsXZE',
    appId: '1:781616472859:android:eaeb1a291c3a7df23de9be',
    messagingSenderId: '781616472859',
    projectId: 'tourmatelk-a98cb',
    storageBucket: 'tourmatelk-a98cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Fv2wiqQ5RgtZseXQN8IeqxQlD3U0Uaw',
    appId: '1:781616472859:ios:ef7cb04f342619673de9be',
    messagingSenderId: '781616472859',
    projectId: 'tourmatelk-a98cb',
    storageBucket: 'tourmatelk-a98cb.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Fv2wiqQ5RgtZseXQN8IeqxQlD3U0Uaw',
    appId: '1:781616472859:ios:ef7cb04f342619673de9be',
    messagingSenderId: '781616472859',
    projectId: 'tourmatelk-a98cb',
    storageBucket: 'tourmatelk-a98cb.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg0AwcQ11I_7Mg-SEm9Aa1QbaV2yRJjUQ',
    appId: '1:781616472859:web:31a06aace679ac0b3de9be',
    messagingSenderId: '781616472859',
    projectId: 'tourmatelk-a98cb',
    authDomain: 'tourmatelk-a98cb.firebaseapp.com',
    storageBucket: 'tourmatelk-a98cb.firebasestorage.app',
    measurementId: 'G-ZNW83RC0F6',
  );
}
